default:
  image: node:latest

pages:
  stage: deploy
  script:
  - npm install
  - yarn cache clean -f
  - yarn run build
  - mv dist publish 
  artifacts:
    paths:
    - publish
  only:
  - master
